# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(max_length=30, null=True, verbose_name='メールアドレス'),
        ),
    ]
